---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.16.2
      helm:
        valueFiles:
          - $values/values/cert-manager.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
