---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-configs
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cert-manager
  source:
    directory:
      exclude: values.yaml
      include: '*'
    path: cert-manager
    repoURL: https://github.com/plcnk/k8s_conf
    targetRevision: HEAD
