---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
spec:
  commonName: unifi.plcnk.home
  dnsNames:
    - unifi.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: unifi-tls
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
