---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
spec:
  commonName: unifi.lab.intra
  dnsNames:
  - unifi.lab.intra
  issuerRef:
    kind: ClusterIssuer
    name: rpllabs-issuer
  secretName: unifi-tls
  subject:
    countries:
    - FR
    localities:
    - Toulouse
    organizations:
    - RPL Labs SAS
    provinces:
    - Haute-Garonne
