---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
spec:
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://charts.plcnk.net
      chart: cloudflare-tunnel
      targetRevision: 0.6.0
      helm:
        valueFiles:
          - $values/values/cloudflared.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
