---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://kubereboot.github.io/charts
      chart: kured
      targetRevision: 5.5.2
      helm:
        valueFiles:
          - $values/values/kured.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
