---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-cert
spec:
  commonName: alertmanager.lab.intra
  dnsNames:
  - alertmanager.lab.intra
  issuerRef:
    kind: ClusterIssuer
    name: rpllabs-issuer
  secretName: alertmanager-tls
  subject:
    countries:
    - FR
    localities:
    - Toulouse
    organizations:
    - RPL Labs SAS
    provinces:
    - Haute-Garonne
