---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
spec:
  commonName: grafana.plcnk.home
  dnsNames:
    - grafana.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: grafana-tls
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
