---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
spec:
  commonName: prometheus.lab.intra
  dnsNames:
  - prometheus.lab.intra
  issuerRef:
    kind: ClusterIssuer
    name: rpllabs-issuer
  secretName: prometheus-tls
  subject:
    countries:
    - FR
    localities:
    - Toulouse
    organizations:
    - RPL Labs SAS
    provinces:
    - Haute-Garonne
