---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
spec:
  destination:
    namespace: it-tools
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://charts.plcnk.net
      chart: it-tools
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/values/it-tools.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
