---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-cnpg-gatus
spec:
  immediate: false
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-gatus
