---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus-cert
spec:
  commonName: gatus.plcnk.home
  dnsNames:
    - gatus.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: gatus-tls
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
