---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
spec:
  encryptedData:
    token: AgBAXx4BXAGBuCQ2PJZVVvJorVAsG0gbyVLOlCF/zrCC53ZyiKZhCZW3IJBmk8SNTYn6FmWj7Yu4tTO0dNRkN+RKesqfaTZOx341xzIFKRfsYYAkuQbk3sXkTnQPKmMFO+HPrhbxS0s3MmIF31SZpptZEj7SQ2E9+0yK2Dm0tXDdi8P61NplE/h905/TCE8HULGSH6pj654mCey/noh6pg4zVjXqi9rN6yNwYegysfmcOx+2wz9Ug6YiajjLgfsurVGLgBmlb9nRO/QZ5t4UMv2XyTEe33AuRRKK15SURRSN4BtrSFQ4rpgJbl2wpAPWlnVbvUzEnCeMFRPXVlmqAdGn5Jvg81xI9WwrIPjsWX900I7gxNCWL/AseZ4flqV07cecguuQ1J14iDJIrllqpGe4wtYsLAzcj79Jkgo16Ay4ldBv1/2Hx6715MOGObt/D787LmjEkEUKPiWaXahk5bEC5JJEPbazCskVr4rKN77aRV5kJi+smc0uH1o1HVBJK0JnBxHZ/O12PONRtNS6ZQgNsNbGYrW5KFGyluOn+yuhvY/VkB6547VadoJ3dd1nFB05m5HQPTggrBE/d4KYxuwEVhnMngqUeLFacuT2wEC21+eoDtMCB8qSJyEy8DNBk1V5xsWQX8W2U228cQBvCIqCtHELiWzskbHyMiOUu6S5zoMYwdpo5UZeqfNIFY/qcPgEH6LaEd3COqjyk0jB+A7ZvtOd6hYz41CPx8KhJ2Oub+KbDiz3DTL+BqLf1UO1npHLzSKjnmZtO4m5oVll2rabyYaYoIzcMAQIQ6YJ/cprNzIyEHg6nejw2hPnQ4xgrrXCbInJipjcBHIMT49QccQxmHPZymvh6PHXPW0EMjKXSU/Eay3+RLP7ofkkUz2MsiZg3t5c9XQOGUWXGpjGCcJiQ8+2Vm16yESVI9TuaelmclBDihT+jGK/
  template:
    metadata:
      name: tunnel-token
