---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-cnpg-gitea
spec:
  immediate: false
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-gitea
