---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-url
spec:
  encryptedData:
    url: AgC9UhYcJJbxrMGUdHlMQGbGsXA9UmK5T/NYMFXkzwP+zxb1FkT+iX8xEJw9x7Nw/SPo3qpfKSHhFu1Ir7SssB0M9M+mIdl04u6VOoK9HS890zF7KHHcU57L1Ktorq0EejcAhubTdc1r6PL666DQVs1zw0c9WQYvdPm6N3b/zlvh9hOmK2QozLNBWMiuztBCTESz8nsx/3uaedldMwlhG+JhcgfBRgNjVUDxZbSUxP8wUiEQcCSFAnWfcvRtDyvuh4RxZf+Dgnt9gDg61ihvbou2u2XxHa7BzlFDPPmsQE9jLPKhgYplePvmOVg8mZytA6JNvgi4qYdtheucFFqugarvfMAOVUzG6HnIp/zzxRfrGSIGyMz6D9evBZKcnvm1JY1S6oSDd/TP1tKsfxSiLOJr282ghFp4HlUujvkbUh237HobQCLt4ezpQhdBJ+w081Rimm7FY6MjOrifk+y3y8fHlR6xaZl+alZOcIWnWhBbPNiz+h0H4m5jffd50QTOVaMDxzAUrdk4k1DtoNUrNj4DCNnhIczltBMELSrtrxcdD4VIL1fHwlxBT45p8D7C5YVummy29rdjPXm0aPkyS8XEgaEpmYEHp4GuVUwpZeSkzNVH2gZNfX11Sy9zFYtmwGK6TX22vq4vCkSnw70iVGG31BxDmOC5Gg6NK+WxTq4Oy6rgJZ5dH/ERDN6uD7S5sFPU1Zpu8T729Rtq0cGvzZWn2VE3LAJE09mbKEmhtrLqxxzStx9NE15HGTWl7DTtt5ARKaavrh/E08UtZTCzf6hARH+BR32kDfk8COO9wxOr2FKp755BJJQ2xq82Re2QuRcfdV9RaSZsBGOhfuO0JrEpxrc/f+ls67LTPPDP
  template:
    metadata:
      name: redis-url
