---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
spec:
  encryptedData:
    password: AgB3+yhxq/DZ43RrfuKX2Z9zT4CRfqxb/v0917AC8rAPnCX/LxeQGTpTe4QaCX1yz0Ngs1Bf2J63D/6NwlHHMnuvNT5svz/f73tgknty7sM+G07NMGJQ0J8tN26ahZQXNhyTMQz4j8beihLppOI9h6vGcMIKQga3xcL6TDz6Gg+vAjEFrTZ7IF3weCzGMLzNqfhca/7CNwmb7UxDulCuiSwm8krUnRYsduGHrk1CpL9PcCQDiPmmkTDkus4OA0luIAzfLem1P29gHwDptyKNvDT3HfKQKEhbHTbWX1byy7j/wnYaEdH656QkmE/17QAH+nnnHomZwj6v0O/5aOQRrt6B2TNNtbX9N++Mn5DQ2P7BF/HW/0g3kqDZMczQQqxFwpvPciNaLIGyTqJ4BfK51rEty6upnbuaIRl/nHR/fFHbsEGxtj0yr+RB3STAneC892Dyagj0K8Z3sbI0oYpEtYsIduxcRquEmyPL6+IKGoNsC3bqLZ8yavNJ6mQnZUla1UzYImjHWa9xCouraJz/HJhahAWxmzLSZEVN/rAjRUxaQEtQV9UVH4HltZigrgRp/1JlonMTGsSedvSfKbqiJ0CPzhgorStw+Lf5t1o7GphdPs2DP7n+xHabaCAsWIAYdvB7NMw9mqvAWNtXP10g+fpjWQVXUAjcC9fiieRXx4dfBv1BRr6p7L2FNSNzraD/BJk8oUNlffQ0oRmnGg7dvIXXm4bits2gMdv07E67a9Q=
  template:
    metadata:
      name: redis-password
