---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ./argocd
  - ./authentik
  - ./cert-manager
  - ./gitea
  - ./ingress-nginx
  - ./prometheus-stack
  - ./rancher
  - ./sealed-secrets
  - ./unifi
  - ./uptime-kuma
