---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-cnpg-wikijs
spec:
  immediate: false
  schedule: "0 0 4 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-wikijs
