---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
spec:
  commonName: auth.plcnk.home
  dnsNames:
    - auth.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: authentik-tls
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
