---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.14.8
      helm:
        valueFiles:
          - $values/values/metallb.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
