---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-cert
spec:
  commonName: rancher.plcnk.home
  dnsNames:
    - rancher.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: tls-rancher-ingress
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
