---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
spec:
  encryptedData:
    address: AgCB2txjqqxL3AryFySEZYt8m7V7fgryOs08JtO9cghHxnIPKa5jYMT+0Jf7BEZCgjvzyqjBpAzcA/UBDMZnKMs7OTxj9HYnT+PkstTcW1Ksr7gz/UN2iWTR+kar3RTd5oE7Yp5NzuNceRPVXshS6FLQ+8t8B95y2MdJ6WeFh6uHQzACSkpLz/gGnDn+MJ803khD5u2VrjgGIwG6mi0ThA6GIXdkxK8lrPVP8mQJ5FWWY/b3THwACuqYA2w8JS6St1sMZpsczWp1/64GYsdL/1IbFYdlu3A81frY6IIbAjnsxCKmv0Kj3LXExnHLrE4K+SUA9Kq/6KsGxdH4pU9CdC7lX4yb7mx+/3CovYIIV3SdiBQpL3UUkw3/S5Yh5UEjXkCBjQMFrHRMHidkSlcZxwNVw/K9boYQvduchNN74B0E4qNNQ3hIWCGDhJwkEzUDqUqz6jgSzHu/sM3r+ifpdeNZDHVMYx9gPb3he17pi0MVOiQ75tJ86zdH+iZfa9Hlc5gjvc2bgVTrrhYbShRj7GKpJQdbRI/JdEUs/GKHRxEPFQX5yQ0rbuszVYB+IAmyBNrjpdjhR+Hx78DmzDu6gcAUYSb9im91X4iJeQA4wyq5jrPl+y3Uat/Oqn71hrsjnq9PQvXyLDXev9QktyiRY/z7SyNCRKdGGf/Idl4K2612GTDqdBnJ8FhsSmft95Sd9HSVNUANqiamF1lTJefr8RXvfmnmnQDdHTgeQYXGC8Gi7LkJbO9MJT70GNJZYYzIbbP/rZUfT8bjygZHbuM5PgRLvEXX8MjuWGZ432Yk43uhYjixQBHXZ1AO0X1d+e3NLByKB664hSCJfjXM1s0QrOKuXLADEnW8tenP
  template:
    metadata:
      name: discord-webhook
