---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd
  - ./authentik
  - ./capacitor
  - ./cert-manager
  - ./gitea
  - ./misc
  - ./prometheus-stack
  - ./rancher
  - ./unifi
