project: ingress-nginx
source:
  repoURL: 'https://kubernetes.github.io/ingress-nginx'
  targetRevision: 4.11.0
  chart: ingress-nginx
destination:
  server: 'https://kubernetes.default.svc'
  namespace: ingress-nginx
