---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
spec:
  commonName: git.plcnk.home
  dnsNames:
    - dash.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: homepage-tls
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
