---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://minicloudlabs.github.io/helm-charts
      chart: gatus
      targetRevision: 3.4.6
      helm:
        valueFiles:
          - $values/values/gatus.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: {}
