---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
spec:
  encryptedData:
    address: AgAA7VcBT8ZVLGf/yfLfvCsKzlZ44f8H7Jqzq2mwDJuVeMhW1grs7tTDBPEEHsrkJv0diicZ8AAHFLIKOg/mrUh+q4jDwVRUg+gnAEL8wSn79ZBCmGEmgZjCjUJ0ybECEW3JzSBjlonl+z7HsrO4TZh1O3e/jQ+Af6wEL0+hbMWEfsu8Jj/5zpmd2di1hYMJmpdXqxm4xWGhJ8WeLkbqo4TqmT9Sbbb0lOU2vBcmw4dA/cBMjbYklsB+sK/S00bcr5X9w5Wh0tAsSmEPdspR1ZQ01dyvUfk2c2iG0HLjTf2kqceOfTT32FNH7XXHylXj5dQWLVOAXoWEmGP51b8md67FfWVGzj5rtkVVNDe6ddwMAFGHTn6lvYragG4FfBOpm/TpqysBIvbui0NBA+jTYC0tGlMLpEpKICNKWW0ISwucB+LuH4g22jaNl5UFRHGgu0C3egZSRV9Pip4s8SA0GpLxJIbv6emb9/rvtKwg9qHGZqI74ZAfC1O0tyhvjwwj93uc4BCoqftvN3jv7UL8MJh6Se02I9niGFC5bS9hjeaj/IMygWoivTZqypeMJVC1/0WpRr4Apz+U4RaakSFCPYPvVeqv8IVsA8WFRFbcgfANInVLqPBowlUxJPGg3nuZkOU0pfgAny8fM8zcUepjCm/r82pt3FbfhDs+/aoBZNoTjgvAEFlgRomlsaklRxBfttCZR3XwoY3VTP1XhwHXZxw/Oprb3VjuQm11fov6rqzFFT6tIVxYMdkXTIRIEoYfwTL1eT4N/tF5idC3GsVhme8RrnaCW5BLeqy1mGYv3fup0ZG9Oq7gv1HdbJdKKGtAfQc+OQ==
  template:
    metadata:
      name: discord-webhook
