---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-cert
spec:
  commonName: status.plcnk.home
  dnsNames:
    - status.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: uptime-kuma-tls
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
