---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-configs
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    directory:
      exclude: values.yaml
      include: '*'
    path: argocd
    repoURL: https://github.com/plcnk/k8s_conf
    targetRevision: HEAD
