---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://dirsigler.github.io/uptime-kuma-helm
      chart: uptime-kuma
      targetRevision: 2.19.1
      helm:
        valueFiles:
          - $values/values/uptime-kuma.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: uptime-kuma
