---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moodist
spec:
  destination:
    namespace: moodist
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://charts.plcnk.net
      chart: moodist
      targetRevision: 0.3.0
      helm:
        valueFiles:
          - $values/values/moodist.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: {}
