---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
spec:
  destination:
    namespace: semaphore
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://cloudhippie.github.io/charts
      chart: ansible-semaphore
      targetRevision: 10.1.3
      helm:
        valueFiles:
          - $values/values/semaphore.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
