---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://dl.gitea.io/charts
      chart: gitea
      targetRevision: 10.4.0
      helm:
        valueFiles:
          - $values/values/gitea.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: gitea
