---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2024.6.1
      helm:
        valueFiles:
          - $values/values/authentik.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/k8s_conf
      targetRevision: HEAD
      ref: values
  project: authentik
