---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: semaphore-cert
spec:
  commonName: semaphore.plcnk.home
  dnsNames:
    - semaphore.plcnk.home
  issuerRef:
    kind: ClusterIssuer
    name: home-issuer
  secretName: semaphore-tls
  subject:
    countries:
      - FR
    localities:
      - Toulouse
    organizations:
      - plcnk Home
    provinces:
      - Haute-Garonne
