---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-semaphore
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  bootstrap:
    initdb:
      database: semaphore
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "15d"
    barmanObjectStore:
      destinationPath: "s3://plcnk-k3s-backups/cnpg-backups"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
