---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
spec:
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: http://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: 2.1.0
      helm:
        valueFiles:
          - $values/values/homepage.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: {}
