---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-controller
spec:
  destination:
    namespace: unifi
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://qonstrukt.github.io/helm-charts
      chart: unifi-controller
      targetRevision: 2.6.1
      helm:
        valueFiles:
          - $values/values/unifi.yaml
    # Values from git
    # This is a test comment (to remove)
    # Another test comment
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: unifi
