---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://cloudnative-pg.io/charts
      chart: cloudnative-pg
      targetRevision: 0.21.6
      helm:
        valueFiles:
          - $values/values/cnpg.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
