---
name: Copy Manifests to Flux Repo

on:
  push:
    branches:
      - master
    paths:
      - argocd-apps/**
      - manifests/**

jobs:
  build:
    name: Copy Manifests to Flux Repo
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Copy Manifests to Flux Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'manifests'
          destination-github-username: 'plcnk'
          destination-repository-name: 'flux-system'
          target-directory: 'k3s/manifests'
          commit-email: 'romain.pluciennik@gmail.com'
          target-branch: master

      - name: Copy Argo CD manifests to Flux Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'argocd-apps'
          destination-github-username: 'plcnk'
          destination-repository-name: 'flux-system'
          target-directory: 'k3s/argocd-apps'
          user-email: 'romain.pluciennik@gmail.com'
          target-branch: master
