---
name: Copy Manifests to Flux Repo

on:
  push:
    branches:
      - master
    paths:
      - argocd-apps/**
      - manifests/**

jobs:
  build:
    name: Copy Manifests to Flux Repo
    runs-on: ubuntu-latest
    steps:
      - name: Copy Manifests to Flux Repo
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'manifests/'
          destination-username: 'plcnk'
          destination-repository: 'flux-system'
          destination-directory: 'k3s/'
          commit-email: 'romain.pluciennik@gmail.com'

      - name: Copy Argo CD manifests to Flux Repo
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'manifests/'
          destination-username: 'plcnk'
          destination-repository: 'flux-system'
          destination-directory: 'k3s/'
          commit-email: 'romain.pluciennik@gmail.com'
