---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  sources:
    # Chart from chart repo
    - repoURL: https://releases.rancher.com/server-charts/latest
      chart: rancher
      targetRevision: 2.9.0
      helm:
        valueFiles:
          - $values/values/rancher.yaml
    # Values from git
    - repoURL: https://github.com/plcnk/kube-configs
      targetRevision: HEAD
      ref: values
  project: default
