---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-cnpg-vaultwarden
spec:
  immediate: true
  schedule: "0 0 5 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-vaultwarden
